# Unit test suite verifying Agent 2 Communication Agent logic, Slack client resilience, and template personalization.  # What: Module header; Why: Verifies Agent 2 and Slack client.
from datetime import datetime, timezone  # What: Import datetime and timezone; Why: Used for timestamps in test models.
import pytest  # What: Import pytest; Why: Test assertion and execution framework.
from src.agents.agent2_communication import Agent2Communication  # What: Import Agent2Communication; Why: Unit under test.
from src.core.audit_logger import audit_logger  # What: Import audit logger; Why: Verifies audit log entries generated by Agent 2.
from src.models.schemas import (  # What: Import domain models; Why: Typed models for test scenarios.
    Agent1Result,  # What: Agent 1 result schema; Why: Input handoff model.
    InboundEmailPayload,  # What: Inbound email model; Why: Supplies customer metadata.
    PlanTier,  # What: Plan tier enum; Why: Enterprise and Growth tiers.
    RocketlaneProjectResponse,  # What: Rocketlane response model; Why: Supplies project portal URL.
    SlackChannelPayload  # What: Slack channel payload; Why: Verifies payload parameters.
)  # What: End of schema imports; Why: Completes domain model dependencies.
from src.services.slack_client import SlackClient  # What: Import SlackClient; Why: Tests Slack client behavior and mock mode.


def test_channel_name_sanitization_rules() -> None:  # What: Test function for channel sanitization; Why: Validates Slack naming constraints.
    """Verifies that customer names with spaces, special characters, and excessive length are properly sanitized."""  # What: Docstring; Why: Explains test intent.
    agent = Agent2Communication(client=SlackClient(mock_mode=True))  # What: Instantiate Agent 2 with mock client; Why: Isolated unit test.

    # 1. Enterprise prefix with spaces and punctuation
    ent_name = agent.sanitize_channel_name("Acme & Sons, Inc.", PlanTier.ENTERPRISE)  # What: Call sanitize_channel_name; Why: Test Enterprise sanitization.
    assert ent_name == "#csm-ent-acme-sons-inc"  # What: Assert sanitized handle; Why: Spaces and punctuation converted to hyphens.

    # 2. Growth prefix with uppercase and numbers
    grw_name = agent.sanitize_channel_name("BetaTech 2026 Solutions", PlanTier.GROWTH)  # What: Call sanitize_channel_name; Why: Test Growth sanitization.
    assert grw_name == "#csm-grw-betatech-2026-solutions"  # What: Assert sanitized handle; Why: Lowercased with growth prefix.

    # 3. Excessive length exceeding Slack's 80-character maximum
    long_company = "A" * 100  # What: Create 100-character name string; Why: Tests length truncation.
    truncated_name = agent.sanitize_channel_name(long_company, PlanTier.ENTERPRISE)  # What: Call sanitize_channel_name; Why: Tests truncation.
    assert len(truncated_name) <= 81  # What: Assert length bounds (80 chars + leading hash); Why: Fits within Slack handle limit.
    assert truncated_name.startswith("#csm-ent-")  # What: Assert correct prefix; Why: Preserves tier prefix.

    # 4. Fallback for names composed purely of special characters
    fallback_name = agent.sanitize_channel_name("$$$ ### @@@", PlanTier.ENTERPRISE)  # What: Call with special chars; Why: Tests empty slug fallback.
    assert fallback_name == "#csm-ent-customer"  # What: Assert default fallback; Why: Guarantees non-empty handle.


def test_channel_topic_embedding_rocketlane_url() -> None:  # What: Test function for topic formatting; Why: Verifies Rocketlane URL embedding.
    """Verifies that the channel topic embeds the Rocketlane project workspace URL and customer plan tier."""  # What: Docstring; Why: Explains test intent.
    agent = Agent2Communication(client=SlackClient(mock_mode=True))  # What: Instantiate Agent 2; Why: Isolated unit test.
    portal_url = "https://app.rocketlane.com/projects/5000000099999"  # What: Sample Rocketlane workspace URL; Why: Expected URL.
    topic = agent.format_channel_topic(portal_url, PlanTier.ENTERPRISE)  # What: Format topic; Why: Executes topic generator.

    assert portal_url in topic  # What: Assert URL presence; Why: Customers need direct workspace access.
    assert "ENTERPRISE" in topic  # What: Assert tier presence; Why: Clarifies plan type.
    assert "NovaCRM Customer Onboarding" in topic  # What: Assert brand presence; Why: Standardized header.


def test_welcome_message_personalization_enterprise() -> None:  # What: Test Enterprise welcome template; Why: Verifies 30d high-touch messaging.
    """Verifies that Enterprise welcome message includes dedicated CSM, 30-day roadmap, and kickoff call link."""  # What: Docstring; Why: Explains test intent.
    agent = Agent2Communication(client=SlackClient(mock_mode=True))  # What: Instantiate Agent 2; Why: Isolated unit test.
    msg = agent.format_welcome_message(  # What: Call format_welcome_message; Why: Generates Enterprise template.
        customer_name="Acme Global",  # What: Customer name; Why: Personalization target.
        tier=PlanTier.ENTERPRISE,  # What: Enterprise tier; Why: Selects enterprise template.
        portal_url="https://app.rocketlane.com/projects/123",  # What: Workspace URL; Why: Portal link.
        csm_name="Sarah Connor (Enterprise Lead)"  # What: Dedicated CSM; Why: Point of contact.
    )  # What: End of method call; Why: Returns generated markdown message.

    assert "Acme Global" in msg  # What: Assert customer name in greeting; Why: Personalized welcome.
    assert "Enterprise Onboarding Program" in msg  # What: Assert program name; Why: Enterprise tier verification.
    assert "30-day timeline" in msg  # What: Assert 30-day SLA; Why: Confirms 30-day duration.
    assert "Sarah Connor (Enterprise Lead)" in msg  # What: Assert dedicated CSM name; Why: High-touch staffing model.
    assert "Phase 1: Kickoff & Architecture Discovery" in msg  # What: Assert phase 1; Why: Roadmap milestone.
    assert "Phase 2: Data Migration & Verification" in msg  # What: Assert phase 2; Why: Verifies data QA milestone.
    assert "calendly.com/novacrm-enterprise/kickoff" in msg  # What: Assert booking link; Why: Kickoff call scheduling.


def test_welcome_message_personalization_growth() -> None:  # What: Test Growth welcome template; Why: Verifies 14d pooled CSM messaging.
    """Verifies that Growth welcome message includes pooled CSM team, 14-day roadmap, and weekly office hours."""  # What: Docstring; Why: Explains test intent.
    agent = Agent2Communication(client=SlackClient(mock_mode=True))  # What: Instantiate Agent 2; Why: Isolated unit test.
    msg = agent.format_welcome_message(  # What: Call format_welcome_message; Why: Generates Growth template.
        customer_name="Beta Startups",  # What: Customer name; Why: Personalization target.
        tier=PlanTier.GROWTH,  # What: Growth tier; Why: Selects growth template.
        portal_url="https://app.rocketlane.com/projects/456",  # What: Workspace URL; Why: Portal link.
        csm_name="Pooled CSM Team"  # What: Pooled team name; Why: Shared resource staffing model.
    )  # What: End of method call; Why: Returns generated markdown message.

    assert "Beta Startups" in msg  # What: Assert customer name; Why: Personalized welcome.
    assert "Growth Fast-Track Onboarding" in msg  # What: Assert program name; Why: Growth tier verification.
    assert "14-day timeline" in msg  # What: Assert 14-day SLA; Why: Confirms 14-day duration.
    assert "Pooled CSM Team" in msg  # What: Assert pooled team; Why: Shared staffing model.
    assert "Weekly Live Office Hours" in msg  # What: Assert office hours support; Why: Group enablement model.
    assert "docs.novacrm.com/getting-started" in msg  # What: Assert docs link; Why: Self-serve enablement.


def test_agent2_skips_when_agent1_halted_missing_data() -> None:  # What: Test precondition failure (missing data); Why: Guardrail skips channel setup.
    """Verifies that Agent 2 halts and skips Slack provisioning if Agent 1 was halted due to missing email data."""  # What: Docstring; Why: Explains test intent.
    agent = Agent2Communication(client=SlackClient(mock_mode=True))  # What: Instantiate Agent 2; Why: Unit under test.
    corr_id = f"test_a2_skip_missing_{int(datetime.now().timestamp())}"  # What: Test correlation ID; Why: Unique trace.

    unconfirmed_result = Agent1Result(  # What: Instantiate unconfirmed Agent 1 result; Why: Simulates missing data halt.
        correlation_id=corr_id,  # What: Correlation ID; Why: Deal trace.
        status="HALTED_MISSING_DATA",  # What: Halted status; Why: Missing mandatory fields.
        rocketlane_project=None  # What: No project created; Why: Upstream halt.
    )  # What: End of unconfirmed result; Why: Ready.

    result = agent.process_project_handoff(unconfirmed_result)  # What: Call process_project_handoff; Why: Executes precondition check.

    assert result.status == "SKIPPED_UNCONFIRMED"  # What: Assert skipped status; Why: Precondition prevented provisioning.
    assert result.provisioning_result is None  # What: Assert no channel created; Why: Guardrail prevented channel creation.
    assert "Slack provisioning skipped" in (result.error_message or "")  # What: Assert descriptive error; Why: Clear rationale.


def test_agent2_skips_when_agent1_escalated_voice_issue() -> None:  # What: Test precondition failure (voice issue); Why: Guardrail skips channel setup.
    """Verifies that Agent 2 skips Slack provisioning if Agent 1 was escalated due to ambiguous or failed telephony."""  # What: Docstring; Why: Explains test intent.
    agent = Agent2Communication(client=SlackClient(mock_mode=True))  # What: Instantiate Agent 2; Why: Unit under test.
    corr_id = f"test_a2_skip_voice_{int(datetime.now().timestamp())}"  # What: Test correlation ID; Why: Unique trace.

    escalated_result = Agent1Result(  # What: Instantiate escalated Agent 1 result; Why: Simulates telephony ambiguity.
        correlation_id=corr_id,  # What: Correlation ID; Why: Deal trace.
        status="ESCALATED_VOICE_ISSUE",  # What: Escalated status; Why: Ambiguous AE phone call.
        rocketlane_project=None  # What: No project created; Why: Upstream halt.
    )  # What: End of escalated result; Why: Ready.

    result = agent.process_project_handoff(escalated_result)  # What: Call process_project_handoff; Why: Executes precondition check.

    assert result.status == "SKIPPED_UNCONFIRMED"  # What: Assert skipped status; Why: Precondition prevented provisioning.
    assert result.provisioning_result is None  # What: Assert no channel created; Why: Guardrail prevented channel creation.


def test_agent2_happy_path_enterprise_mock_provisioning() -> None:  # What: Test complete successful handoff; Why: Verifies channel, topic, and message.
    """Verifies that a successful Agent 1 Enterprise result triggers channel creation, topic setting, and welcome message."""  # What: Docstring; Why: Explains test intent.
    agent = Agent2Communication(client=SlackClient(mock_mode=True))  # What: Instantiate Agent 2; Why: Unit under test.
    corr_id = f"test_a2_happy_ent_{int(datetime.now().timestamp())}"  # What: Test correlation ID; Why: Unique trace.

    # Build confirmed Agent 1 Enterprise outcome
    agent1_result = Agent1Result(  # What: Instantiate successful Agent 1 result; Why: Simulates completed Enterprise onboarding intake.
        correlation_id=corr_id,  # What: Correlation ID; Why: Deal trace.
        status="SUCCESS",  # What: Status SUCCESS; Why: Successfully provisioned.
        email_payload=InboundEmailPayload(  # What: Inbound email model; Why: Customer metadata.
            message_id="msg_123",  # What: Message ID; Why: Email ID.
            customer_name="Globex Corporation",  # What: Customer name; Why: Name to sanitize.
            customer_contact_email="it@globex.com",  # What: Customer email; Why: Primary collaborator.
            ae_name="Hank Scorpio",  # What: AE name; Why: Deal owner.
            ae_phone="+1-555-0100"  # What: AE phone; Why: Contact phone.
        ),  # What: End of email payload; Why: Ready.
        rocketlane_project=RocketlaneProjectResponse(  # What: Rocketlane response model; Why: Provisioned project data.
            project_id="5000000088888",  # What: Rocketlane project ID; Why: Workspace reference.
            project_name="Globex Corporation - Onboarding (ENTERPRISE)",  # What: Project title; Why: Display title.
            tier=PlanTier.ENTERPRISE,  # What: Enterprise tier; Why: Confirmed plan.
            template_id="5000000095997",  # What: Template ID; Why: 30-day template.
            portal_url="https://app.rocketlane.com/projects/5000000088888",  # What: Portal URL; Why: Embedded link.
            is_duplicate=False  # What: Not duplicate; Why: Fresh project.
        )  # What: End of project response; Why: Ready.
    )  # What: End of Agent 1 result; Why: Complete input.

    result = agent.process_project_handoff(agent1_result)  # What: Call process_project_handoff; Why: Executes Agent 2 workflow.

    # Assertions on successful Agent 2 execution
    assert result.status == "SUCCESS"  # What: Assert status SUCCESS; Why: Workflow succeeded.
    assert result.provisioning_result is not None  # What: Assert provisioning result exists; Why: Slack channel was created.
    assert result.provisioning_result.channel_name == "csm-ent-globex-corporation"  # What: Assert sanitized handle; Why: Enterprise slug verified.
    assert result.provisioning_result.channel_id.startswith("C_MOCK_")  # What: Assert mock channel ID; Why: Mock provisioning verified.
    assert result.provisioning_result.topic_set is True  # What: Assert topic set; Why: Rocketlane link embedded.
    assert result.provisioning_result.welcome_message_ts is not None  # What: Assert message timestamp; Why: Welcome message delivered.

    # Verify structured audit trail for this deal
    entries = audit_logger.get_entries_for_correlation(corr_id)  # What: Retrieve audit trail entries; Why: Verifies logging compliance.
    actions = [e.action for e in entries]  # What: Extract action names list; Why: Inspects executed steps.
    assert "process_handoff_started" in actions  # What: Assert start logged; Why: Initial event captured.
    assert "slack_channel_creation_started" in actions  # What: Assert channel creation logged; Why: Channel creation event captured.
    assert "slack_topic_set" in actions  # What: Assert topic logged; Why: Topic embedding captured.
    assert "slack_welcome_message_posted" in actions  # What: Assert message logged; Why: Message posting captured.
    assert "agent2_workflow_completed" in actions  # What: Assert completion logged; Why: Final outcome captured.
